AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: '
Resources:
  Hello:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.serverless.Handler
      Runtime: java8
      CodeUri: build/libs/hello-dev-all.jar
      MemorySize: 128
      Timeout: 3
  GetWishList:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.wishlist.GetWishLists
      Runtime: java8
      CodeUri: build/libs/hello-dev-all.jar
      MemorySize: 1024
      Timeout: 10
